User.create!([
  {email: "admin@test.com", password:'123abc', encrypted_password: "$2a$11$7wkFb5pYGkUCXfb9vCgOr.zQ5IVfeTzV4M7zGNr68qTf7Ji645wd6", username: nil, reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2018-01-07 01:58:58", last_sign_in_at: "2018-01-07 01:58:58", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}
])
Assignment.create!([
  {user_id: 1, role_id: 1}
])
Post.create!([
  {image_data: "{\"id\":\"b8a6fb14c39beed2468028fdd35d629a.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"01-Bruno-Mars-and-cardi-b-Finesse-screenshot-billboard-1548.jpg\",\"size\":76298,\"mime_type\":\"image/jpeg\"}}", title: "Bruno Mars – Finesse ft. Cardi B (Remix)", description: "<div>Cardi B may have got he co-sign of her life with pop superstar Bruno Mars calling on her to feature on his smash hit single “Finesse”. Watch the video for “Finesse”</div>", embed_files: "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/LsoLEjrDogU\" frameborder=\"0\" gesture=\"media\" allow=\"encrypted-media\" allowfullscreen></iframe>", category: "videos", authord_id: 1, featured: false, spotlighted: false},
  {image_data: "{\"id\":\"8a23752e0fa411fee00bffcc84b1b87d.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"a-boogie-with-a-hoodie-opener-c114326f-f73e-45b9-8b8e-0801d8bd5e86.jpg\",\"size\":50476,\"mime_type\":\"image/jpeg\"}}", title: "A Boogie Wit Da Hoodie – Say A", description: "<div>A Boogie Wit Da Hoodie releases his visual for his single “Say A” off of his The Bigger Artist project. Check out the new music video and let us know what you think!</div>", embed_files: "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/DVbKboc8XmE\" frameborder=\"0\" gesture=\"media\" allow=\"encrypted-media\" allowfullscreen></iframe>", category: "videos", authord_id: 1, featured: false, spotlighted: false},
  {image_data: "{\"id\":\"3d7592e13707b5eb880654ca46704931.png\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"plies.png\",\"size\":459457,\"mime_type\":\"image/png\"}}", title: "Plies – Rock", description: "<div>Watch the official music video for “Rock” by Plies.<br>“Ain’t No Mixtape Bih 3” out now!</div>", embed_files: "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/PHQ097mhs8I\" frameborder=\"0\" gesture=\"media\" allow=\"encrypted-media\" allowfullscreen></iframe>", category: "videos", authord_id: 1, featured: true, spotlighted: false},
  {image_data: "{\"id\":\"fad4b02cfa406f1848e4a820cd50214a.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"dont-judge-me-feat-future-swae-lee-750-750-1508371140-34u7rtjc9zziyc9ac1a39c.jpg\",\"size\":8445,\"mime_type\":\"image/jpeg\"}}", title: "Ty Dolla Sign – Don’t Judge Me Ft. Future & Swae Lee", description: "<div><strong>Ty Dolla Sign links up with Future &amp; Swae Lee for a brand new hit single “Don’t Judge Me”. As Ty Dolla Sign gears up for </strong><strong><em>Beach House 3’s</em></strong><strong> release, he’s been dropping different singles off the project. Check out the new joint and let us know what you think!</strong></div>", embed_files: "<iframe src=\"https://audiomack.com/embed/song/mixtape-republic/dont-judge-me\" scrolling=\"no\" width=\"100%\" height=\"252\" scrollbars=\"no\" frameborder=\"0\"></iframe>", category: "music", authord_id: 1, featured: false, spotlighted: false},
  {image_data: "{\"id\":\"5d996c5793d83a168efb39cda6d9dd05.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"lil uzi.jpg\",\"size\":14274,\"mime_type\":\"image/jpeg\"}}", title: "Lil Uzi Vert, TM88 & Southside – Mood", description: "<div><strong>Some of the biggest names in Hip Hop team up on this hot new blazing track we have here. Lil Uzi Vert, TM88 and Southside team up on their new song “Mood”.</strong></div>", embed_files: "<iframe width=\"100%\" height=\"300\" scrolling=\"no\" frameborder=\"no\" src=\"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/379402637&amp;color=%23ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true\"></iframe>", category: "music", authord_id: 1, featured: false, spotlighted: false},
  {image_data: "{\"id\":\"a7882e3c69063ccce9fd37c4388f8819.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"1515168037_aba89b7653c8b90e6bb87542bf49f91e-35cqmvbnmgj53y37i5dczk.jpg\",\"size\":9890,\"mime_type\":\"image/jpeg\"}}", title: "Hoodrich Pablo Juan – Street Punk Ft. Lil Yachty", description: "<div><strong>Hoodrich Pablo Juan calls on Lil Yachty for his newest single “Street Punk”.</strong></div>", embed_files: "<iframe width=\"100%\" height=\"300\" scrolling=\"no\" frameborder=\"no\" src=\"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/379178075&amp;color=%23ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true\"></iframe>", category: "music", authord_id: 1, featured: false, spotlighted: false},
  {image_data: "{\"id\":\"5c0cbb3a4dd6922cea3472ea2cd75635.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"kevinmcall.jpg\",\"size\":56812,\"mime_type\":\"image/jpeg\"}}", title: "KEVIN MCCALL THREATENS TO PUT CHRIS BROWN AND HIS DAUGHTER ROYALTY IN A CASKET IF HE FINDS OUT CHRIS SHOT HIM", description: "<div>Kevin McCall has no filter at all, the once Chris Brown Best Friend let it be known that if Chris Brown had anything to do with him being shot Chris and his daughter Royalty would be in a casket. Kevin wrote this on his verified twitter account. Check all his comments below.</div>", embed_files: "<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">I don’t see wat I said wrong. The Bible says and eye for and eye...Chris didn’t do it so don’t bring his name up in my life and death situation because you playing with gossip but L.A ain’t a game. I didn’t threaten anyone I told you how life would play out. I saved him hella X’s</p>&mdash; Kevin McCall (@KevinMcCallJr) <a href=\"https://twitter.com/KevinMcCallJr/status/949694758632374272?ref_src=twsrc%5Etfw\">January 6, 2018</a></blockquote>\r\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\r\n\r\n<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">Tell me in person. U do cocaine. Not much you can’t judge about you need AA lol I’m saying stop putting Chris Brown in my life and death situation it’s people who will kill him. So if u have a problem with what I said tell me in person not on social media this is called reaching <a href=\"https://t.co/jtoE1ftjNK\">https://t.co/jtoE1ftjNK</a></p>&mdash; Kevin McCall (@KevinMcCallJr) <a href=\"https://twitter.com/KevinMcCallJr/status/949693723348103168?ref_src=twsrc%5Etfw\">January 6, 2018</a></blockquote>\r\n\r\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\r\n<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">It’s what people have tired to do in the past the person who shot even tried to kill him for 500$ and I fought him for it. So if someone does Kill me for what I said..again it’s gonna harm a lot of people for a long time don’t try to make CB look Gangster clown me &amp; leave CB be. <a href=\"https://t.co/KplHirM7Uu\">https://t.co/KplHirM7Uu</a></p>&mdash; Kevin McCall (@KevinMcCallJr) <a href=\"https://twitter.com/KevinMcCallJr/status/949697285776031744?ref_src=twsrc%5Etfw\">January 6, 2018</a></blockquote>\r\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\r\n\r\n", category: "news", authord_id: 1, featured: true, spotlighted: false},
  {image_data: "{\"id\":\"92f1b2b579e2147a8f1b24e248d5eba6.png\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"Screen-Shot-2018-01-05-at-2.34.34-PM-35cj7p8yzc60htg87e6sjk.png\",\"size\":329038,\"mime_type\":\"image/png\"}}", title: "THE MAURY SHOW WELCOMES CARDI B ON THE SHOW TO GIVE OFFSET A LIE DETECTOR TEST FOR HIS CHEATING", description: "<div>Damn this OffSet cheating on Cardi B scandal is officially getting out of hand. Now we have a tweet from the verified twitter account of The Maury Show which shows Maury tweeting Cardi B inviting her on his show to Lie detector test OffSet. Maury wrote Cardi <strong>“</strong>if you ever need a Lie Detector Test or have more relationship drama…you know you can always call Uncle Maury!<strong>“<br></strong><br></div><div>No word on if Cardi has seen the tweet, but we must admit this is pretty funny from Maury lol. Check all the tweets below<br><br></div>", embed_files: "<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">.<a href=\"https://twitter.com/iamcardib?ref_src=twsrc%5Etfw\">@iamcardib</a> if you ever need a Lie Detector Test or have more relationship drama...you know you can always call Uncle Maury!</p>&mdash; The Maury Show (@TheMAURYShow) <a href=\"https://twitter.com/TheMAURYShow/status/949272075713335298?ref_src=twsrc%5Etfw\">January 5, 2018</a></blockquote>\r\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\r\n\r\n<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">Isn&#39;t easier to take him to <a href=\"https://twitter.com/TheMAURYShow?ref_src=twsrc%5Etfw\">@TheMAURYShow</a>?  Let Uncle Maury get to the bottom of it! <a href=\"https://twitter.com/hashtag/Maury20?src=hash&amp;ref_src=twsrc%5Etfw\">#Maury20</a> <a href=\"https://t.co/OMX3ahMmwe\">https://t.co/OMX3ahMmwe</a></p>&mdash; The Maury Show (@TheMAURYShow) <a href=\"https://twitter.com/TheMAURYShow/status/949270099629834240?ref_src=twsrc%5Etfw\">January 5, 2018</a></blockquote>\r\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\r\n\r\n<blockquote class=\"twitter-tweet\" data-lang=\"en\"><p lang=\"en\" dir=\"ltr\">You&#39;re weak?   How do you think <a href=\"https://twitter.com/iamcardib?ref_src=twsrc%5Etfw\">@iamcardib</a> feels? <a href=\"https://t.co/rliyD4xR4y\">https://t.co/rliyD4xR4y</a></p>&mdash; The Maury Show (@TheMAURYShow) <a href=\"https://twitter.com/TheMAURYShow/status/949329960153559040?ref_src=twsrc%5Etfw\">January 5, 2018</a></blockquote>\r\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\r\n", category: "news", authord_id: 1, featured: true, spotlighted: false},
  {image_data: "{\"id\":\"3c0b04d43e208dad718b116b28381fe5.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"Donald-Trump-big-mouth-img.jpg\",\"size\":151591,\"mime_type\":\"image/jpeg\"}}", title: "Trump Might Order 200,000 Salvadorans to Leave US After Being Here 20 Years", description: "<div>On Monday, the Trump administration will face a deadline to decide the fate of nearly 200,000 Salvadorans who have been living in the U.S under temporary legal immigration status for almost 20 years.<br><br></div><div><br>Both the Department of Homeland Security and the White House have signaled for months that they are determined to end the TPS (temporary protected status) protections as a matter of principle.<br><br></div><div><br>This would result in the Salvadorans being forced to leave or face deportation if they do not find another way to obtain legal residency.<br><br></div><div><br>Many Salvadorans believe the U.S. should come up with another way to allow them to stay. The Salvadoran Embassy in Washington guesses that 97% of Salvadorans on TPS over the age of 24 are employed and paying taxes, and more than half own their own homes.<br><br></div><div><br>According to a report from the Center for Migration Studies, Salvadorans on TPS have also given birth to 192,000 children, all U.S. citizens.<br><br></div><div><br>\"Congress should consider the humanity, the dignity, of these families and give them some kind of a solution,\" said Murillo, who serves on the national board of the National TPS Alliance. \"There are children who have been born in this country. These are families who have given their best to this country. To then, after 17 years, be told to abandon it?\"<br><br></div>", embed_files: "", category: "news", authord_id: 1, featured: false, spotlighted: false},
  {image_data: "{\"id\":\"10e602c7f77d56783e9577784db075b1.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"video-237256-355au6shqgl4cdz3q9fz0g.jpg\",\"size\":31829,\"mime_type\":\"image/jpeg\"}}", title: "LAMBORGHINI UNLEASHES ITS NEW SUV “THE URUS” PRICED AT $200,000", description: "<div>Lamborghini is stepping back into the SUV market with their second SUV ever in the brands history. The Urus will be released in 2018. Lamborghini CEO Stefano Domenicali gave his thoughts on the Urus saying <strong>“The Lamborghini Urus is a visionary approach based on the infusion of Lamborghini DNA into the most versatile vehicle, the SUV.” He went on to say “The Urus elevates the SUV to a level not previously possible, the Super SUV. It is a true Lamborghini in terms of design, performance, driving dynamics and emotion as well as drivable every day in a range of environments.”<br></strong><br></div><div>The car specs are rumored that it can go from 0-to-62 MPH in 3.6 seconds, and can also go from 0-to-124 MPH in 12.8 seconds. The Urus can also reach a maxium speed of 190 MPH. The Urus has a 4.0-litre V twin-turbo engine, and an automatic eight-speed gearbox.<br><br></div><div>The Urus also features different driving modes to help the driver navigate. The modes are CORSA, SPORT, SABBIA (sand), NEVE (snow), TERRA (off-road), and STRADA.<br><br></div><div>The URUS will release in Spring 2018 at a price of $200,000 USD, and a plug-in hybrid model is expected to drop in 2020.<br><br><br></div>", embed_files: "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/vX_P_uo15Yo\" frameborder=\"0\" gesture=\"media\" allow=\"encrypted-media\" allowfullscreen></iframe>", category: "lifestyle", authord_id: 1, featured: false, spotlighted: false},
  {image_data: "{\"id\":\"b07ecb5eea431c9ee1371726b2964547.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"jordan-3-black-cement-february-2018-release-date-2.jpg\",\"size\":143431,\"mime_type\":\"image/jpeg\"}}", title: "AIR JORDAN 3 BLACK/CEMENT TO RELEASE IN FEBRUARY AFTER 17 YEARS", description: "<div>The Air Jordan 3 “Black Cement” is a black and grey version of Michael Jordan’s third signature shoe. It originally released in 1988, followed by 1994, 2001, 2008, and 2011 featuring a mix of leather, elephant print, and visible Air. The shoe releases again with Remastered OG “Nike Air” branding on Michael Jordan’s birthday, February 17th, 2018 for $200 in celebration of the sneaker’s 30th Anniversary.</div>", embed_files: "", category: "lifestyle", authord_id: 1, featured: true, spotlighted: false},
  {image_data: "{\"id\":\"d6477db2515792d41d2bf4280fc7a9d6.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"katrina-air-jordan-3-35am658yckwfeaibcmb474.jpg\",\"size\":27327,\"mime_type\":\"image/jpeg\"}}", title: "FIRST LOOK AT AIR JORDAN 3 “KATRINA”", description: "<div>The Air Jordan 3 “Katrina” was originally drawn up over 12 years ago in order to raise funds for Hurricane Katrina Victims. While the sneaker never made a wide release, it is scheduled to do just that early next year. Last week, we brought you the first look at actual images of the “Fire Red” and “Cement” 3 hybrid, and now brings a closer view of the design. Similar to the initial images of the “Black Cement” 3 that surfaced, these images are of a kids-size version which is the reason for the oversized perforations on the lace and heel panelling. Enjoy an up-close look at the Air Jordan 3 “Katrina” below and mark your calendars for May 12th, when this pair is scheduled to arrive at Jordan Brand retailers.</div>", embed_files: "", category: "lifestyle", authord_id: 1, featured: false, spotlighted: false}
])
Role.create!([
  {name: "Admin"},
  {name: "content_manager"}
])
Tag.create!([
  {name: "cardi b"},
  {name: "bruno mars"},
  {name: "finesse"},
  {name: "A Boogie Wit Da Hoodie"},
  {name: "say a"},
  {name: "plies"},
  {name: "rock"},
  {name: "Ty Dolla Sign"},
  {name: "Don’t Judge Me"},
  {name: "Future"},
  {name: "Swae Lee"},
  {name: "Lil Uzi Vert"},
  {name: "TM88"},
  {name: "Southside"},
  {name: "Mood"},
  {name: "Hoodrich Pablo Juan"},
  {name: "Street Punk"},
  {name: "Lil Yachty"},
  {name: "kevin mccall"},
  {name: "gunshot"},
  {name: "CHRIS BROWN"},
  {name: "MAURY"},
  {name: "CARDI B"},
  {name: "Donald Trump"},
  {name: "LAMBORGHINI"},
  {name: "THE URUS"},
  {name: "AIR JORDAN 3"},
  {name: "Katrina"}
])
Tagging.create!([
  {tag_id: 1, post_id: 1},
  {tag_id: 2, post_id: 1},
  {tag_id: 3, post_id: 1},
  {tag_id: 4, post_id: 2},
  {tag_id: 5, post_id: 2},
  {tag_id: 6, post_id: 3},
  {tag_id: 7, post_id: 3},
  {tag_id: 8, post_id: 4},
  {tag_id: 9, post_id: 4},
  {tag_id: 10, post_id: 4},
  {tag_id: 11, post_id: 4},
  {tag_id: 12, post_id: 5},
  {tag_id: 13, post_id: 5},
  {tag_id: 14, post_id: 5},
  {tag_id: 15, post_id: 5},
  {tag_id: 16, post_id: 6},
  {tag_id: 17, post_id: 6},
  {tag_id: 18, post_id: 6},
  {tag_id: 19, post_id: 7},
  {tag_id: 20, post_id: 7},
  {tag_id: 21, post_id: 7},
  {tag_id: 22, post_id: 8},
  {tag_id: 23, post_id: 8},
  {tag_id: 24, post_id: 9},
  {tag_id: 25, post_id: 10},
  {tag_id: 26, post_id: 10},
  {tag_id: 27, post_id: 11},
  {tag_id: 27, post_id: 12},
  {tag_id: 28, post_id: 12}
])
